mediamarkt:
  selector: 'div[data-test="mms-price"] span:nth-of-type(2)'
  type: "html"
  skus:
    - id: iphone15-128
      url: "https://www.mediamarkt.ch/de/product/_apple-iphone-15-2203371.html"

interdiscount:
  selector: "script[type='application/ld+json']"
  type: "json-ld"
  json_path: "offers.price"
  skus:
    - id: iphone15-128
      url: "https://www.interdiscount.ch/fr/product/apple-iphone-15-128-gb-noir-6-1-48-mp-5g-0013899644"

brack:
  selector: "script#b2c-pdp-datalayer"
  type: "json"
  json_path: "prod[0].price"
  skus:
    - id: iphone15-128
      url: "https://www.brack.ch/apple-iphone-15-128-gb-schwarz-1618405"
