name: Trigger auto deployment for scheduler-job

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/scheduler-job-AutoDeployTrigger-dc34f194-090b-44ad-a476-78f9e4780336.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCHEDULERJOB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCHEDULERJOB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCHEDULERJOB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}scheduler
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SCHEDULERJOB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCHEDULERJOB_REGISTRY_PASSWORD }}
          containerAppName: scheduler-job
          resourceGroup: galaxus-demo
          imageToBuild: valentinneher/scheduler-job:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


